#!/usr/bin/env python

import os

if 'VIRTUAL_ENV' in os.environ:

    os.system("pip install .")

else:

    print("ERROR: Please install in a virtualenv")
    print("       Consult the cloudmesh client manual")